### PR TITLE
Add more keys to .env template. Fix typo in development.rb missing ke…

### PR DESCRIPTION
**Pull request by jcavena**
…ys message.

### CODE REVIEW

**Comment by jcavena** [comment]
I'm ignoring the remaining two houndci suggestions.

**Comment by pachacamac** [comment]
You could use

`env_var_missing = -> { "xxx".tap { STDERR.puts "ENV VAR MISSING! SHOULDN'T MATTER THOUGH SINCE WE'RE IN DEVELOPMENT" } }`

to get rid of one of those violations.

Otherwise :+1:

**Comment by jcavena** [comment]
Good point. I just wasn't really bothered by that.

**Comment by kalimar** [comment]
Houndci-bot is totally trolling you guys.

Can you just add a specific comment that tells houndci to ignore?

**Comment by pachacamac** [comment]
@kalimar good point. @houndci-bot is using rubocop, therefore a simple `.rubocop.yml` file in the project root should suffice. https://houndci.com/configuration#ruby

**Comment by jcavena** [comment]
Yes, we can config it. Will probably turn off noisy stuff. Or add a specific "JC's code sucks" rule in there.

**Comment by pachacamac** [comment]
To be fair, those two violations were targeting my shitty code :3

**Pull request merged**
